#!/usr/bin/env python3
"""
Propose Lifecycle Rule Changes

This script reads the output from identify_delete_markers.py and generates
proposed lifecycle rule changes to enable "Remove expired delete markers"
for buckets that need it.

Usage:
    python propose_lifecycle_rule.py --input results.csv --output proposals.json
    python propose_lifecycle_rule.py --input results.csv --terraform
"""

import argparse
import csv
import json
import sys
from typing import Dict, List, Any


def read_csv_results(filename: str) -> List[Dict]:
    """Read CSV results from identify_delete_markers.py"""
    results = []
    with open(filename, "r") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            results.append(row)
    return results


def generate_lifecycle_proposal(bucket_name: str, account_id: str) -> Dict:
    """Generate a lifecycle rule proposal for removing expired delete markers"""
    return {
        "bucket_name": bucket_name,
        "account_id": account_id,
        "proposed_rule": {
            "id": "remove-expired-delete-markers",
            "status": "Enabled",
            "expiration": {
                "expired_object_delete_marker": True
            },
            "filter": {}
        },
        "description": "Enable removal of expired delete markers to clean up versioned bucket",
        "terraform_resource": f"""
# Add to lifecycle configuration for bucket: {bucket_name}
rule {{
  id     = "remove-expired-delete-markers"
  status = "Enabled"

  expiration {{
    expired_object_delete_marker = true
  }}
}}
"""
    }


def generate_proposals(results: List[Dict], output_format: str) -> List[Dict]:
    """Generate lifecycle rule proposals for buckets that need them"""
    proposals = []
    
    for result in results:
        # Only propose for buckets that need attention and don't have the rule
        if (result["status"] == "needs_attention" and 
            result["has_lifecycle_delete_marker_rule"] == "False"):
            
            proposal = generate_lifecycle_proposal(
                result["bucket_name"],
                result["account_id"]
            )
            proposals.append(proposal)
    
    return proposals


def write_json_output(proposals: List[Dict], filename: str):
    """Write proposals as JSON"""
    with open(filename, "w") as f:
        json.dump(proposals, f, indent=2)


def write_terraform_output(proposals: List[Dict], filename: str):
    """Write proposals as Terraform configuration snippets"""
    with open(filename, "w") as f:
        f.write("# Terraform Lifecycle Rule Proposals\n")
        f.write("# Generated by propose_lifecycle_rule.py\n\n")
        
        for proposal in proposals:
            f.write(f"# Bucket: {proposal['bucket_name']}\n")
            f.write(f"# Account: {proposal['account_id']}\n")
            f.write(proposal["terraform_resource"])
            f.write("\n" + "-" * 80 + "\n\n")


def print_summary(proposals: List[Dict]):
    """Print summary of proposals"""
    print("\n" + "=" * 80)
    print("LIFECYCLE RULE PROPOSALS")
    print("=" * 80)
    print(f"Total proposals: {len(proposals)}")
    print()
    
    if proposals:
        print("BUCKETS REQUIRING LIFECYCLE RULE:")
        print("-" * 80)
        for proposal in proposals:
            print(f"  {proposal['bucket_name']}")
            print(f"    Account: {proposal['account_id']}")
            print(f"    Description: {proposal['description']}")
            print()


def main():
    parser = argparse.ArgumentParser(
        description="Generate lifecycle rule proposals from delete marker analysis"
    )
    parser.add_argument(
        "--input",
        "-i",
        required=True,
        help="Input CSV file from identify_delete_markers.py"
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output filename (default: proposals.json or proposals.tf)"
    )
    parser.add_argument(
        "--terraform",
        action="store_true",
        help="Output as Terraform configuration instead of JSON"
    )
    
    args = parser.parse_args()
    
    # Read input CSV
    try:
        results = read_csv_results(args.input)
    except FileNotFoundError:
        print(f"Error: Input file '{args.input}' not found", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading input file: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Generate proposals
    proposals = generate_proposals(results, "terraform" if args.terraform else "json")
    
    # Determine output filename
    if args.output:
        output_filename = args.output
    else:
        output_filename = "proposals.tf" if args.terraform else "proposals.json"
    
    # Write output
    if args.terraform:
        write_terraform_output(proposals, output_filename)
    else:
        write_json_output(proposals, output_filename)
    
    # Print summary
    print_summary(proposals)
    print(f"\nProposals written to: {output_filename}")


if __name__ == "__main__":
    main()

